name = "Academic-SD"
license = "MIT"
licenselink = "https://github.com/Shaunakde/hugo-academic/blob/master/LICENSE.md"
description = "Fork of the Hugo Academic theme, adjusted to my tastes."
homepage = "https://github.com/Shaunakde/hugo-academic"
min_version = 0.30
tags = ["academic",
        "portfolio",
        "responsive",
        "student",
        "personal",
        "university",
        "blog",
        "minimal"
        ]
features = ["academic profile",
            "research publication system",
            "projects",
            "blog",
            "teaching",
            "contact"
            ]

[author]
  name = "Shaunak De"
  homepage = "https://shaunak.de"

# If porting an existing theme
[original]
  name = "George Cushen"
  homepage = "https://georgecushen.com"
  repo = "https://github.com/gcushen/hugo-academic"
